import Head from 'next/head'
import Navigation from '@/components/Navigation';
import AnimateSlide from '@/components/AnimateSlide';
import { useForm } from 'react-hook-form';
import { Button, FormControl } from '@mui/material';
import axios from 'axios';

const FormFields = {
  name: '',
  email: '',
  message: ''
};

export default function Projects() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const submitForm = (data: any) => {
    console.log(data);

    // send post request to api
    axios.post('https://formspree.io/f/xrgvnyla', data)
      .then((response) => {
        console.log(response);
      })
      .catch((error) => {
        console.log(error);
      });

  }
  return (
    <>
      <Head>
        <title>Ideen Banijamali</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="all" />
      </Head>
      <div className=''>
        <AnimateSlide direction='down' delay={200}>
          <Navigation />
        </AnimateSlide>

        <div className='flex flex-wrap gap-14 p-4'>
          <div className='grid m-auto bg-zinc-700 h-fit md:h-1/2 w-full lg:w-3/5 rounded-3xl'>
            <div className='grid grid-cols-1 h-full md:grid-cols-2 place-items-center p-8'>
              <div className='grid h-full w-full md:border-r-2 content-center'>
                <div className='grid m-5 place-items-center'>
                  <div className='grid h-full w-full gap-2'>
                    <h1 className='grid text-3xl font-bold text-white'>Contact Me!</h1>
                    <p className='text-white'>Whether it&apos;s new opportunities, freelance tasks, or you just wanna get in touch, I&apos;m always happy to chat. Feel free to drop me a message and I&apos;ll get back to you as soon as possible.</p>
                  </div>
                </div>
              </div>
              <div className='grid h-full w-full place-content-center'>
                <div className='grid w-64 justify-self-start '>
                  <form onSubmit={handleSubmit((data) => submitForm(data))}method="POST">
                    <FormControl className='gap-2'>
                      {Object.entries(FormFields).map(([key, value]) => (
                        <div key={key}>
                          <label className='grid text-2xl font-bold text-white'>{key}</label>
                          <input className='grid w-full p-2 m-2 text-black rounded-lg' {...register(key)} type={key} />
                        </div>
                      ))}

                      <Button style={{ backgroundColor: 'green' }} variant="contained" type='submit'>Submit</Button>
                    </FormControl>
                  </form>
                  <div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
