import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '@/components/Navigation';
import AboutCard from '@/components/AboutCard';
import AnimateSlide from '@/components/AnimateSlide';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ideen Banijamali</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="all" />
      </Head>
      <div className='w-screen h-screen'>
       
        <div className='grid h-1/6 w-full '>
          <AnimateSlide direction='down' delay={1000}>
            <Navigation />
          </AnimateSlide>
        </div>
        <div className='h-5/6 w-full content-start p-5 lg:p-0 Z-10'>
          <AnimateSlide direction='right'>
            <AboutCard />
          </AnimateSlide>

        </div>

      </div>
    </>
  )
}
