import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '@/components/Navigation';
import AboutCard from '@/components/AboutCard';
import AnimateSlide from '@/components/AnimateSlide';
import { useCallback } from "react";
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const particlesInit = useCallback(async (engine: Engine) => {
    console.log(engine);

    // you can initialize the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(async (container: Container | undefined) => {
    await console.log(container);
  }, []);
  return (
    <>
      <Head>
        <title>Ideen Banijamali</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="all" />
      </Head>
      <div className='w-screen h-screen'>
       
        <div className='grid h-1/6 w-full '>
          <AnimateSlide direction='down' delay={1000}>
            <Navigation />
          </AnimateSlide>
        </div>
        <div className='h-5/6 w-full content-start p-5 lg:p-0 Z-10'>
          <AnimateSlide direction='right'>
            <AboutCard />
          </AnimateSlide>

        </div>

      </div>
    </>
  )
}
