import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '@/components/Navigation';
import AnimateSlide from '@/components/AnimateSlide';
import { useState } from 'react';
import ProjectCard from '@/components/ProjectCard';

const inter = Inter({ subsets: ['latin'] })

type IProject = {
  title: string;
  description: string;
  image: string;
  link: string;
}

export default function Projects() {

  const [projects, setProjects] = useState<IProject[]>([
    {
      title: 'Project 1',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/1.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 2',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/2.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 1',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/1.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 2',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/2.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 1',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/1.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 2',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/2.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 1',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/1.jpg',
      link: 'https://google.com'
    },
    {
      title: 'Project 2',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
      image: '/images/2.jpg',
      link: 'https://google.com'
    }
  ]);

  return (
    <>
      <Head>
        <title>Ideen Banijamali</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="all" />
      </Head>
      <div className=''>
        <AnimateSlide direction='down' delay={200}>
          <Navigation />
        </AnimateSlide>

        <div className='flex flex-wrap gap-14 p-4'>
          {projects.map((project, index) => (
            <AnimateSlide direction='up' delay={(index + 1) * 300} key={index}>
              <ProjectCard
                title={project.title}
                description={project.description}
                image={project.image}
                link={project.link}
              />
            </AnimateSlide>
          ))}
        </div>

      </div>
    </>
  )
}
